# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

#
## PARENT MENU
#

[[main]]
name = "About Us"
pre = "circle-info"
pageRef = "about"
weight = 10

[[main]]
name = "Projects"
pre = "heart"
pageRef = "projects"
weight = 20

[[main]]
name = "Info/Writings"
pre = "lightbulb"
pageRef = "info"
weight = 30

[[main]]
name = "Howto/Guides"
pre = "shield"
pageref = "guides"
weight = 40

#
## Projects

[[main]]
name = "Community Workshops & Trainings"
pre = "graduation-cap"
parent = "Projects"
pageRef = "projects/workshops"
weight = 10

[[main]]
name = "UpRiv|Upcycle: Community E-Waste Reclamation Program"
pre = "sun"
parent = "Projects"
pageRef = "projects/upcycle"
weight = 20

[[main]]
name = "Community-Owned Media"
pre = "rss-square"
parent = "Projects"
pageRef = "projects/media"
weight = 30

[[main]]
name = "Youth Code Camp"
pre = "code"
parent = "Projects"
pageRef = "projects/code-camp"
weight = 40

[[main]]
name = "Solar-Powered, Mutual-Aid Comms Network"
pre = "globe"
parent = "Projects"
pageRef = "projects/mesh"
weight = 50

[[main]]
name = "Secure Data Erasure"
pre = "bomb"
parent = "Projects"
pageRef = "projects/secure-shred"
weight = 60

#
## Howto/Guides

[[main]]
name = "Privacy 101"
pre = "lock"
parent = "Howto/Guides"
pageRef = "guides/privacy101/1-intro/"
weight = 10

[[main]]
name = "Advanced Privacy"
pre = "pgpkey"
parent = "Howto/Guides"
pageRef = "guides/advanced/1-threat-model/"
weight = 20

[[main]]
name = "Android Privacy Guide"
pre = "phone"
parent = "Howto/Guides"
pageRef = "guides/android"
weight = 30

#
## Info/Writings

[[main]]
name = "Points of Unity"
pre = "scale-balanced"
parent = "Info/Writings"
pageRef = "info/points_of_unity"
weight = 10

[[main]]
name = "AI Reality Check"
pre = "eye"
parent = "Info/Writings"
pageRef = "info/ai_literacy"
weight = 20

[[main]]
name = "The Reverse Centaur"
pre = "triangle-exclamation"
parent = "Info/Writings"
pageRef = "info/reverse_centaur"
weight = 22

[[main]]
name = "Animism, AI & Consciousness"
pre = "sun"
parent = "Info/Writings"
pageRef = "info/ai_animism"
weight = 26

[[main]]
name = "A Critical History of the Internet"
pre = "list"
parent = "Info/Writings"
pageRef = "info/internet_history"
weight = 35

[[main]]
name = "What is Techno-Colonialism?"
pre = "globe"
parent = "Info/Writings"
pageRef = "info/technocolonialism"
weight = 30

[[main]]
name = "Neo-Luddism: Peasant Revolts Against Predatory Tech"
pre = "fire"
parent = "Info/Writings"
pageRef = "info/technofeudalism"
weight = 40

[[main]]
name = "What is #Data Back?"
pre = "shield"
parent = "Info/Writings"
pageRef = "info/data_back"
weight = 50

[[main]]
name = "Age Verification Laws"
pre = "triangle-exclamation"
parent = "Info/Writings"
pageRef = "info/age_verification"
weight = 60

[[main]]
name = "What is a 'Feminist Server Stack'?"
pre = "heart"
parent = "Info/Writings"
pageRef = "info/femme_srv"
weight = 70

[[main]]
name = "Hacker Culture"
pre = "bug"
parent = "Info/Writings"
pageRef = "info/hacker_manifesto"
weight = 80

[[main]]
name = "Maker Space Culture"
pre = "wand-magic-sparkles"
parent = "Info/Writings"
pageRef = "info/makers"
weight = 90

[[main]]
name = "Modern-day Oracles or Bullshit Machines: How to thrive in a ChatGPT world"
pre = "poo"
parent = "Info/Writings"
url = "https://thebullshitmachines.com/index.html"
weight = 100

#
## SUB-NAV

[[subnavigation]]
  name = "SUBSCRIBE"
  pre = "envelope"
  pageRef = "subscribe"
  weight = 30

[[subnavigation]]
  name = "NEWS"
  pre = "rss-square"
  pageRef = "links"
  weight = 25

[[subnavigation]]
#  name = "🄳🄾🄽🄰🅃🄴"
#  name = "DONATE"
#  pre = "donation"
#  pageRef = "subscribe"
#  #url = "https://list.klamathtech.diy/subscription/form"
#  weight = 20

#-- Footer Menu --
#The footer menu is displayed at the bottom of the page, just before
#the copyright notice. Configure as per the main menu above.

[[footer]]
name = "Tags"
pageRef = "tags"
weight = 10

[[footer]]
name = "Categories"
pageRef = "categories"
weight = 20

[[footer]]
name = "Authors"
pageRef = "authors"
weight = 30
